$(document).ready(function(){
	//$("*").css("color","#0000ff");
	//$("#nome").css("color","#0000ff");
	//$(".p2").css("color","#0000ff");
	//$("span").css("color","#0000ff");
	//$(".p2,#nome").css("color","#0000ff");
	//$("p span".css("color","0000ff");
	//$("p > span".css("color","0000ff");
	//$(".p2 + span").css("border","1px solid #ff00ff");
	//$("#nome + p").css("border","1px solid #ff00ff");
	//$("p + span").css("border","1px solid #ff00ff");
	//$("#nome ~ p").css("border","1px solid #ff00ff");
	//$("*").css("border","1px solid #ff00ff");
	//$("p span").css("border","1px solid #ff00ff");
	//$("p span:first").css("border","1px solid #ff00ff");
	//$("p span:last").css("border","1px solid #ff00ff");
	//$("p span:not(p span:first)").css("border","1px solid #ff00ff");
	//$("p span:even").css("border","1px solid #ff00ff");
	//$("p span:odd").css("border","1px solid #ff00ff");
	//$("p span:eq(2)").css("border","1px solid #ff00ff");
	//$("p span:gt(0)").css("border","1px solid #ff00ff");
	//$("p span:lt(2)").css("border","1px solid #ff00ff");
	//$("p:contains(p1)").css("border","1px solid #ff00ff");
	//$("p:empty").css("border","1px solid #ff00ff");
	//$("p:not(p:empty)").css("border","1px solid #ff00ff");
	//$("p:has(span)").css("border","1px solid #ff00ff");
	//$("a[id]").css("border","1px solid #ff00ff");
	//$("a[id=google]").css("border","1px solid #ff00ff");
	//$("a[id*=m]").css("border","1px solid #ff00ff");
	//$("a[href$=rar]").css("border","1px solid #ff00ff");
	//$("a[id^=http]").css("border","1px solid #ff00ff");
	$("a[id!=google]").css("border","1px solid #ff00ff");
});
