$(document).ready(function(){
	$("span").css("border","2px solid #00ff00");
	$("#esconde").click(function(){
		//$("img").hide();
		//$("img").hide("slow");
		//$("img").hide("normal");
		//$("img").hide("fast");
		$("img").hide(4000);
	});
	$("#mostra").click(function(){
		//$("img").show();
		//$("img").show("slow");
		//$("img").show("normal");
		//$("img").show("fast");
		$("img").show(10000);
	});
	$("#alterna").click(function(){
		//$("img").toggle();
		//$("img").toggle("slow");
		//$("img").toggle("normal");
		//$("img").toggle("fast");
		$("img").toggle(2000);
	});
	$("#opacidadeS").click(function(){
		//$("img").fadeOut();
		//$("img").fadeOut("slow");
		//$("img").fadeOut("normal");
		//$("img").fadeOut("fast");
		$("img").fadeOut(2000);
	});
	$("#opacidadeE").click(function(){
		//$("img").fadeIn();
		//$("img").fadeIn("slow");
		//$("img").fadeIn("normal");
		//$("img").fadeIn("fast");
		$("img").fadeIn(2000);
	});
	$("#opacidade50").click(function(){
		//$("img").fadeTo();
		//$("img").fadeTo("slow",0.5);
		//$("img").fadeTo("normal",0.5);
		//$("img").fadeTo("fast",0.5);
		$("img").fadeTo(2000,0.5);
	});
	$("#opacidadeA").click(function(){
		//$("img").fadeToggle();
		//$("img").fadeToggle("slow");
		//$("img").fadeToggle("normal");
		//$("img").fadeToggle("fast");
		$("img").fadeToggle(2000);
	});
	$("#deslocaC").click(function(){
		//$("img").slideUp();
		//$("img").slideUp("slow");
		//$("img").slideUp("normal");
		//$("img").slideUp("fast");
		$("img").slideUp(2000);
	});
	$("#deslocaB").click(function(){
		//$("img").slideDown();
		//$("img").slideDown("slow");
		//$("img").slideDown("normal");
		//$("img").slideDown("fast");
		$("img").slideDown(2000);
	});
});